name: Publish to Clojars

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: clojars
          server-username: grayskull-oss
          server-password: ${{ secrets.DEPLOY_TOKEN }}
      - name: Store gpg key
        run: echo $GPG_SIGNING_KEY_BASE64 | base64 -d > /tmp/gpg.key
        env:
          GPG_SIGNING_KEY_BASE64: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Build with Maven
        run: |
          echo gpg key
          cat /tmp/gpg.key
          ./mvnw -B clean install gpg:sign -Dgpg.signer=bc
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
      - name: Deploy spi to Clojars
        run: |
          cd spi/
          ./mvnw -B deploy
      - name: Deploy server to Clojars
        run: |
          cd server/
          ./mvnw -B deploy
      - name: Deploy derby-async-audit to Clojars
        run: |
          cd derby-async-audit/
          ./mvnw -B deploy
